name: Integrate

on:
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up Biome
        uses: biomejs/setup-biome@v2
      - name: Run Biome
        run: biome ci

  test:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up pnpm
        uses: pnpm/action-setup@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version-file: .node-version
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run typecheck
        run: pnpm typecheck
      - name: Run tests
        run: pnpm test
      - name: Build package
        run: pnpm build
